export const fieldsConfig = [
  { key: 'fullName', label: '姓名', merge: ['firstName', 'lastName'], join: ' ' },
  { key: 'fullFurigana', label: 'ふりがな', merge: ['firstNameFurigana', 'lastNameFurigana'], join: ' ' },
  { key: 'fullRomaji', label: '罗马字', merge: ['firstNameRomaji', 'lastNameRomaji'], join: ' ' },
  { key: 'gender', label: '性别' },
  { key: 'birth', label: '出生年月日' },
  { key: 'age', label: '年龄' },
  { key: 'nationality', label: '国籍' },
  { key: 'visa', label: '在留资格' },
  { key: 'visaOther', label: '在留资格' },
  { key: 'jobs', label: '工种' },
  { key: 'expYear', label: '经验年数' },
  { key: 'insuranceDate', label: '劳灾保险到期' },
  { key: 'zip', label: '邮编' },
  { key: 'address', label: '住址' },
  { key: 'phone', label: '电话' },
  { key: 'healthDate', label: '健康诊断日' },
  { key: 'bloodPressure', label: '血压', merge: ['bpHigh', 'bpLow'], format: (high: string | number, low: string | number) => `高/${high} 低/${low}` },
  { key: 'blood', label: '血型' },
  { key: 'emgName', label: '紧急联系人姓名' },
  { key: 'emgFurigana', label: '紧急联系人姓名' },
  { key: 'emgPhone', label: '紧急联系人电话' },
  { key: 'relationship', label: '与本人关系' },
  { key: 'emgZip', label: '紧急联系人邮编' },
  { key: 'emgAddress', label: '紧急联系人住址' },
]; 